spring.config.activate.on-profile: dev
spring:
  application:
    name: conversation-app-dev
  jpa:
    show-sql: true
    properties:
      format_sql: true
management:
  endpoint:
    shutdown:
      enabled: true
#logging:
#  level:
#    org:
#      springframework:
#        modulith: debug
#        security: debug
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace
#        SQL: debug